### ISSUE TITLE
[Bug] Only Creator Can Start Race

### ISSUE THREAD

**Issue by Brusein** [ItsANoBrainer/qb-racing#7]
Only person who can start a race is the creator, is there a way to call for the person who setup the race?

Reason I ask is I'm an option 1 guy who imported a ton of races made by someone else. 

Thank you!

**Comment by ItsANoBrainer** [comment]
I will investigate this today and resolve this issue so whoever setup the race can start it.

**Comment by Brusein** [comment]
Thank you so much, I tried to tinker and couldn't get it. Please let me know if you would like me to test it for you as well. Appreciate the work and starred the repository!

**Comment by ItsANoBrainer** [comment]
@Brusein Fixed in latest version.

**Comment by Brusein** [comment]
> @Brusein Fixed in latest version.

Thank you so much, is there a way I can DM you on discord? Have a question about a key fob idea for my sever and may need some advice.

**Comment by ItsANoBrainer** [comment]
Yes

**Comment by Brusein** [comment]
Ok what is you Discord info, I looked but didn’t see it.

Thank you so much again!

**Comment by Brusein** [comment]
Here is mine if you want to DM me instead Bru#1198
